name: Build and Deploy to Some Server
on:
  push:
    branches:
      - main
      - sandbox
env:
  GITHUB_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: npm install, test and build
        run: |
          echo "SECRET_KEY=${SECRET_KEY}" >> .env
          echo "${{ env.GITHUB_ACTION_URL }}"
          npm install
          npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, test and build
        run: |
          echo "deploying to server"
