name: Build assets
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build assets
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: |
          git config --global user.email "it@positivegrid.com" 
          git config --global user.name "Bot"

      - name: List files in the main branch
        run: |
          ls ${{ github.workspace }}
        
      - uses: actions/checkout@v3
        with:
          ref: main-build
      - name: List files in the main-build
        run: |
          ls ${{ github.workspace }}

      - run: git merge main -m "merge"
      - run: npm install
      - run: npm run build
      - run: git add .
      - run: git diff-index --quiet HEAD || git commit -m 'Production build by bot'
      - run: git push main-build