# on:
#   workflow_dispatch:
#     inputs:
#       example_input:
#         description: 'An example input'
#         required: false
#         default: 'hello'
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print input
#         run: echo "Input is ${{ github.event.inputs.example_input }}"

on:
  repository_dispatch:
    types: [external-trigger]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Do something
        run: echo "Triggered by repository_dispatch"    